name: flutter_start
description: Starter UI for flutter project creation

publish_to: 'none' 
version: 1.1.0+2

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  clipboard: ^0.1.3
  cupertino_icons: ^1.0.2
  dio: ^5.3.0
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.3.6
  freezed_annotation: ^2.1.0
  go_router: ^10.0.0
  json_annotation: ^4.6.0
  json_serializable: ^6.3.1
  logger: ^1.1.0
  retrofit: ^4.0.1
  url_launcher: ^6.1.5
  websafe_svg: ^3.0.1+1

dev_dependencies:
  custom_lint:
  riverpod_lint:
  build_runner: ^2.2.0
  flutter_lints: ^2.0.2
  flutter_test:
    sdk: flutter
  freezed: ^2.1.0+1
  mockito: ^5.4.2
  retrofit_generator:

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    
    
                                      