name: flutter_start
description: Starter UI for flutter project creation

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  clipboard: ^0.1.3
  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  freezed_annotation: ^2.1.0
  get_it: ^7.2.0
  go_router: ^4.1.0
  json_annotation: ^4.6.0
  json_serializable: ^6.3.1
  logger: ^1.1.0
  retrofit: ^3.0.1+1
  url_launcher: ^6.1.5
  websafe_svg: ^2.1.2+1

dev_dependencies:
  build_runner: ^2.2.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.1.0+1
  retrofit_generator: ^4.0.2

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    
    
                                      